### PR TITLE
upgrade to react 18

### PR DESCRIPTION
**Pull request by renoiser**
yo @nogizhopaboroda i'm back :D .
I wonder if we can upgrade to react 18, I guess it should be fine.

### CODE REVIEW

**Comment by nogizhopaboroda** [comment]
hey @renoiser , i had to rollback react to version 17. seems like it's way more work than expected with this update. current working branch for version 18 upgrade is `migrate-to-react-18` (https://github.com/audio-node/web-noise/pull/131/files)

**Comment by renoiser** [comment]
ahhh damn! @nogizhopaboroda do u have any details about the issues u encountered with react 18?

**Comment by renoiser** [comment]
@nogizhopaboroda just checked the [PR](https://github.com/audio-node/web-noise/pull/131/files), LGTM ✌️

**Comment by nogizhopaboroda** [comment]
@renoiser the branch is still WIP. There is one major issue that is reproducible on all nodes: `Invalid hook call` (https://legacy.reactjs.org/warnings/invalid-hook-call-warning.html) . Currently my guess that it's due to multipackage structure of the app, so probably there are several versions of react as a peer dependency or so. Don't know so far, still researching/debugging

**Pull request merged**
